name: Build and Push Ollama Image

# 添加权限配置
permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build-and-push:
    strategy:
      matrix:
        model: ['smollm2:135m', 'qwen:0.5b']
    runs-on: ubuntu-latest

    steps:
    # Checkout代码库
    - name: Checkout Code
      uses: actions/checkout@v3

    # 登录GitHub容器注册表
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 启动Ollama服务并拉取模型
    - name: Start Ollama Service and Pull Models
      run: |
        docker run -d --name ollama \
          -v $PWD/models:/root/.ollama/models \
          ollama/ollama:latest 
        sleep 5
        docker exec ollama \
          sh -c "ollama pull ${{ matrix.model }}"
        sleep 1
        docker rm -f ollama

    # 构建新的镜像
    - name: Build Docker Image
      run: |
        MODEL_NAME=$(echo "${{ matrix.model }}" | sed 's/:/-/g' | tr '[:upper:]' '[:lower:]')
        USER_NAME=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/${USER_NAME}/ollama-${MODEL_NAME}:latest .

    # 推送镜像到GitHub容器注册表
    - name: Push Docker Image
      run: |
        MODEL_NAME=$(echo "${{ matrix.model }}" | sed 's/:/-/g' | tr '[:upper:]' '[:lower:]')
        USER_NAME=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/${USER_NAME}/ollama-${MODEL_NAME}:latest
